# Generated by Django 2.2.6 on 2019-11-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='descriptionCategorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
